# DATA SCIENCE AND MACHINE LEARNING INTERNSHIP

# FINAL PROJECT:

### Mobile phone price fixed on the various factors like processor, RAM,Internal memory etc There are 21 features given in the dataset.Classify the mobile price range as 0,1,2 or 3 based upon the features given in the dataset.

### Class 0 – low cost
### Class 1 – medium cost
### Class 2 - high cost
### Class 3 – very high cost

### SVM algorithm(Support vector machine)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")

In [3]:
train

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [4]:
test

,id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,1,1043,1,1.8,1,14,0,5,0.1,193,...,16,226,1412,3476,12,7,2,0,1,0
1,2,841,1,0.5,1,4,1,61,0.8,191,...,12,746,857,3895,6,0,7,1,0,0
2,3,1807,1,2.8,0,1,0,27,0.9,186,...,4,1270,1366,2396,17,10,10,0,1,1
3,4,1546,0,0.5,1,18,1,25,0.5,96,...,20,295,1752,3893,10,0,7,1,1,0
4,5,1434,0,1.4,0,11,1,49,0.5,108,...,18,749,810,1773,15,8,7,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,1700,1,1.9,0,0,1,54,0.5,170,...,17,644,913,2121,14,8,15,1,1,0
996,997,609,0,1.8,1,0,0,13,0.9,186,...,2,1152,1632,1933,8,1,19,0,1,1
997,998,1185,0,1.4,0,1,1,8,0.5,80,...,12,477,825,1223,5,0,14,1,0,0
998,999,1533,1,0.5,1,0,0,50,0.4,171,...,12,38,832,2509,15,11,6,0,1,0
999,1000,1270,1,0.5,0,4,1,35,0.1,140,...,19,457,608,2828,9,2,3,1,0,1

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.2 KB

In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   battery_power  1000 non-null   int64
 2   blue           1000 non-null   int64
 3   clock_speed    1000 non-null   float64
 4   dual_sim       1000 non-null   int64
 5   fc             1000 non-null   int64
 6   four_g         1000 non-null   int64
 7   int_memory     1000 non-null   int64
 8   m_dep          1000 non-null   float64
 9   mobile_wt      1000 non-null   int64
 10  n_cores        1000 non-null   int64
 11  pc             1000 non-null   int64
 12  px_height      1000 non-null   int64
 13  px_width       1000 non-null   int64
 14  ram            1000 non-null   int64
 15  sc_h           1000 non-null   int64
 16  sc_w           1000 non-null   int64
 17  talk_time      1000 non-null   int64
 18  three_g        1000 non-null   int64
 19  touch_screen   1000 non-null   int64
 20  wifi           1000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 164.2 KB

### Data preprocessing

In [7]:
train.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
battery_power,2000.0,1238.51850,439.418206,501.0,851.75,1226.0,1615.25,1998.0
blue,2000.0,0.49500,0.500100,0.0,0.00,0.0,1.00,1.0
clock_speed,2000.0,1.52225,0.816004,0.5,0.70,1.5,2.20,3.0
dual_sim,2000.0,0.50950,0.500035,0.0,0.00,1.0,1.00,1.0
fc,2000.0,4.30950,4.341444,0.0,1.00,3.0,7.00,19.0
four_g,2000.0,0.52150,0.499662,0.0,0.00,1.0,1.00,1.0
int_memory,2000.0,32.04650,18.145715,2.0,16.00,32.0,48.00,64.0
m_dep,2000.0,0.50175,0.288416,0.1,0.20,0.5,0.80,1.0
mobile_wt,2000.0,140.24900,35.399655,80.0,109.00,141.0,170.00,200.0
n_cores,2000.0,4.52050,2.287837,1.0,3.00,4.0,7.00,8.0
pc,2000.0,9.91650,6.064315,0.0,5.00,10.0,15.00,20.0
px_height,2000.0,645.10800,443.780811,0.0,282.75,564.0,947.25,1960.0
px_width,2000.0,1251.51550,432.199447,500.0,874.75,1247.0,1633.00,1998.0
ram,2000.0,2124.21300,1084.732044,256.0,1207.50,2146.5,3064.50,3998.0
sc_h,2000.0,12.30650,4.213245,5.0,9.00,12.0,16.00,19.0
sc_w,2000.0,5.76700,4.356398,0.0,2.00,5.0,9.00,18.0
talk_time,2000.0,11.01100,5.463955,2.0,6.00,11.0,16.00,20.0
three_g,2000.0,0.76150,0.426273,0.0,1.00,1.0,1.00,1.0
touch_screen,2000.0,0.50300,0.500116,0.0,0.00,1.0,1.00,1.0
wifi,2000.0,0.50700,0.500076,0.0,0.00,1.0,1.00,1.0
price_range,2000.0,1.50000,1.118314,0.0,0.75,1.5,2.25,3.0

### checking if there are any missing values:

In [8]:
train.isnull()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
test.isnull()

,id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

### checking if there are any duplicate values:

In [10]:
train.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [11]:
test.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

### In train.csv the px_height column has irrevalent data so we replace px_height column values with their mean values

In [12]:
print(train['px_height'].all())

False

In [13]:
train['px_height'].replace(0, train['px_height'].mean(), inplace=True)

In [14]:
print(train['px_height'].all())

True

In [15]:
train.all()

battery_power     True
blue             False
clock_speed       True
dual_sim         False
fc               False
four_g           False
int_memory        True
m_dep             True
mobile_wt         True
n_cores           True
pc               False
px_height         True
px_width          True
ram               True
sc_h              True
sc_w             False
talk_time         True
three_g          False
touch_screen     False
wifi             False
price_range      False
dtype: bool

### checking correlation between the columns

In [16]:
train.corr()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
battery_power,1.000000,0.011252,0.011482,-0.041847,0.033334,0.015665,-0.004004,0.034085,0.001844,-0.029727,...,0.015337,-0.008402,-0.000653,-0.029959,-0.021421,0.052510,0.011522,-0.010516,-0.008343,0.200723
blue,0.011252,1.000000,0.021419,0.035198,0.003593,0.013443,0.041177,0.004049,-0.008605,0.036161,...,-0.006865,-0.041533,0.026351,-0.002952,0.000613,0.013934,-0.030236,0.010061,-0.021863,0.020573
clock_speed,0.011482,0.021419,1.000000,-0.001315,-0.000434,-0.043073,0.006545,-0.014364,0.012350,-0.005724,...,-0.013597,-0.009476,0.003443,-0.029078,-0.007378,-0.011432,-0.046433,0.019756,-0.024471,-0.006606
dual_sim,-0.041847,0.035198,-0.001315,1.000000,-0.029123,0.003187,-0.015679,-0.022142,-0.008979,-0.024658,...,-0.022381,0.014291,0.041072,-0.011949,-0.016666,-0.039404,-0.014008,-0.017117,0.022740,0.017444
fc,0.033334,0.003593,-0.000434,-0.029123,1.000000,-0.016560,-0.029133,-0.001791,0.023618,-0.013356,...,-0.009769,-0.005176,0.015099,-0.011014,-0.012373,-0.006829,0.001793,-0.014828,0.020085,0.021998
four_g,0.015665,0.013443,-0.043073,0.003187,-0.016560,1.000000,0.008690,-0.001823,-0.016537,-0.029706,...,-0.017862,0.007448,0.007313,0.027166,0.037005,-0.046628,0.584246,0.016758,-0.017620,0.014772
int_memory,-0.004004,0.041177,0.006545,-0.015679,-0.029133,0.008690,1.000000,0.006886,-0.034214,-0.028310,...,0.009566,-0.008335,0.032813,0.037771,0.011731,-0.002790,-0.009366,-0.026999,0.006993,0.044435
m_dep,0.034085,0.004049,-0.014364,-0.022142,-0.001791,-0.001823,0.006886,1.000000,0.021756,-0.003504,...,0.024524,0.023566,-0.009434,-0.025348,-0.018388,0.017003,-0.012065,-0.002638,-0.028353,0.000853
mobile_wt,0.001844,-0.008605,0.012350,-0.008979,0.023618,-0.016537,-0.034214,0.021756,1.000000,-0.018989,...,0.000375,0.000090,-0.002581,-0.033855,-0.020761,0.006209,0.001551,-0.014368,-0.000409,-0.030302
n_cores,-0.029727,0.036161,-0.005724,-0.024658,-0.013356,-0.029706,-0.028310,-0.003504,-0.018989,1.000000,...,-0.005938,0.024480,0.004868,-0.000315,0.025826,0.013148,-0.014733,0.023774,-0.009964,0.004399
pc,0.031441,-0.009952,-0.005245,-0.017143,0.644595,-0.005598,-0.033273,0.026282,0.018844,-0.001193,...,-0.018345,0.004196,0.028984,0.004938,-0.023819,0.014657,-0.001322,-0.008742,0.005389,0.033599
px_height,0.015337,-0.006865,-0.013597,-0.022381,-0.009769,-0.017862,0.009566,0.024524,0.000375,-0.005938,...,1.000000,0.512011,-0.019433,0.058881,0.041992,-0.010526,-0.030392,0.023361,0.050403,0.149666
px_width,-0.008402,-0.041533,-0.009476,0.014291,-0.005176,0.007448,-0.008335,0.023566,0.000090,0.024480,...,0.512011,1.000000,0.004105,0.021599,0.034699,0.006720,0.000350,-0.001628,0.030319,0.165818
ram,-0.000653,0.026351,0.003443,0.041072,0.015099,0.007313,0.032813,-0.009434,-0.002581,0.004868,...,-0.019433,0.004105,1.000000,0.015996,0.035576,0.010820,0.015795,-0.030455,0.022669,0.917046
sc_h,-0.029959,-0.002952,-0.029078,-0.011949,-0.011014,0.027166,0.037771,-0.025348,-0.033855,-0.000315,...,0.058881,0.021599,0.015996,1.000000,0.506144,-0.017335,0.012033,-0.020023,0.025929,0.022986
sc_w,-0.021421,0.000613,-0.007378,-0.016666,-0.012373,0.037005,0.011731,-0.018388,-0.020761,0.025826,...,0.041992,0.034699,0.035576,0.506144,1.000000,-0.022821,0.030941,0.012720,0.035423,0.038711
talk_time,0.052510,0.013934,-0.011432,-0.039404,-0.006829,-0.046628,-0.002790,0.017003,0.006209,0.013148,...,-0.010526,0.006720,0.010820,-0.017335,-0.022821,1.000000,-0.042688,0.017196,-0.029504,0.021859
three_g,0.011522,-0.030236,-0.046433,-0.014008,0.001793,0.584246,-0.009366,-0.012065,0.001551,-0.014733,...,-0.030392,0.000350,0.015795,0.012033,0.030941,-0.042688,1.000000,0.013917,0.004316,0.023611
touch_screen,-0.010516,0.010061,0.019756,-0.017117,-0.014828,0.016758,-0.026999,-0.002638,-0.014368,0.023774,...,0.023361,-0.001628,-0.030455,-0.020023,0.012720,0.017196,0.013917,1.000000,0.011917,-0.030411
wifi,-0.008343,-0.021863,-0.024471,0.022740,0.020085,-0.017620,0.006993,-0.028353,-0.000409,-0.009964,...,0.050403,0.030319,0.022669,0.025929,0.035423,-0.029504,0.004316,0.011917,1.000000,0.018785
price_range,0.200723,0.020573,-0.006606,0.017444,0.021998,0.014772,0.044435,0.000853,-0.030302,0.004399,...,0.149666,0.165818,0.917046,0.022986,0.038711,0.021859,0.023611,-0.030411,0.018785,1.000000

In [17]:
(train.corr()["price_range"]* 100).sort_values(ascending=False)

price_range      100.000000
ram               91.704574
battery_power     20.072261
px_width          16.581750
px_height         14.966627
int_memory         4.443496
sc_w               3.871127
pc                 3.359930
three_g            2.361122
sc_h               2.298607
fc                 2.199821
talk_time          2.185887
blue               2.057285
wifi               1.878481
dual_sim           1.744448
four_g             1.477171
n_cores            0.439927
m_dep              0.085304
clock_speed       -0.660569
mobile_wt         -3.030217
touch_screen      -3.041107
Name: price_range, dtype: float64

### as the correlation of some parameters are very low they can be ignored or dropped because they are not much useful for the prediction process

In [18]:
train.drop(labels=['blue', 'dual_sim', 'm_dep', 'mobile_wt','four_g', 'talk_time', 'clock_speed','touch_screen','n_cores'], inplace=True, axis=1)

In [19]:
train.all()

battery_power     True
fc               False
int_memory        True
pc               False
px_height         True
px_width          True
ram               True
sc_h              True
sc_w             False
three_g          False
wifi             False
price_range      False
dtype: bool

### as there are irrelevent values in above columns replace them with mean values

In [20]:
train['pc'].replace(0, train['pc'].mean(), inplace=True)

In [21]:
train['sc_w'].replace(0, train['sc_w'].mean(), inplace=True)

In [22]:
train['three_g'].replace(0, train['three_g'].mean(), inplace=True)

In [23]:
train['wifi'].replace(0, train['wifi'].mean(), inplace=True)

In [24]:
train['fc'].replace(0, train['fc'].mean(), inplace=True)

In [25]:
train.all()

battery_power     True
fc                True
int_memory        True
pc                True
px_height         True
px_width          True
ram               True
sc_h              True
sc_w              True
three_g           True
wifi              True
price_range      False
dtype: bool

In [26]:
x_train=train

In [27]:
x_train.shape

(2000, 12)

In [28]:
x_train.head()

,battery_power,fc,int_memory,pc,px_height,px_width,ram,sc_h,sc_w,three_g,wifi,price_range
0,842,1.0000,7,2.0,20.0,756,2549,9,7.0,0.7615,1.000,1
1,1021,4.3095,53,6.0,905.0,1988,2631,17,3.0,1.0000,0.507,2
2,563,2.0000,41,6.0,1263.0,1716,2603,11,2.0,1.0000,0.507,2
3,615,4.3095,10,9.0,1216.0,1786,2769,16,8.0,1.0000,0.507,2
4,1821,13.0000,44,14.0,1208.0,1212,1411,8,2.0,1.0000,0.507,1

## Y_TRAIN

### as there is a price_range column in y_train(which is the predicted column) that should be dropped from trained data set

In [29]:
y_train = train['price_range']
train.drop(['price_range'], inplace=True, axis=1)

In [30]:
y_train.shape

(2000,)

In [31]:
y_train=pd.DataFrame(y_train)

In [32]:
y_train.head()

   price_range
0            1
1            2
2            2
3            2
4            1

## X_TRAIN

### after dropping price_range column remaining data should be placed in the x_train

In [33]:
x_train=train

In [34]:
x_train.shape

(2000, 11)

In [35]:
x_train.head()

,battery_power,fc,int_memory,pc,px_height,px_width,ram,sc_h,sc_w,three_g,wifi
0,842,1.0000,7,2.0,20.0,756,2549,9,7.0,0.7615,1.000
1,1021,4.3095,53,6.0,905.0,1988,2631,17,3.0,1.0000,0.507
2,563,2.0000,41,6.0,1263.0,1716,2603,11,2.0,1.0000,0.507
3,615,4.3095,10,9.0,1216.0,1786,2769,16,8.0,1.0000,0.507
4,1821,13.0000,44,14.0,1208.0,1212,1411,8,2.0,1.0000,0.507

### as id column is not required for prediction process we drop that column

In [36]:
ids= test['id'] 
test.drop('id', inplace=True, axis=1)

In [37]:
test.all()

battery_power     True
blue             False
clock_speed       True
dual_sim         False
fc               False
four_g           False
int_memory        True
m_dep             True
mobile_wt         True
n_cores           True
pc               False
px_height        False
px_width          True
ram               True
sc_h              True
sc_w             False
talk_time         True
three_g          False
touch_screen     False
wifi             False
dtype: bool

### as the correlation of some parameters are very low they can be ignored or dropped because they are not much useful for the prediction process

In [38]:
test.drop(labels=['blue', 'dual_sim', 'm_dep', 'mobile_wt','four_g', 'talk_time', 'clock_speed','touch_screen','n_cores'], inplace=True, axis=1)

In [39]:
test.shape

(1000, 11)

In [40]:
test.all()

battery_power     True
fc               False
int_memory        True
pc               False
px_height        False
px_width          True
ram               True
sc_h              True
sc_w             False
three_g          False
wifi             False
dtype: bool

In [41]:
test['px_height'].replace(0, test['px_height'].mean(), inplace=True)
test['pc'].replace(0, test['pc'].mean(), inplace=True)
test['sc_w'].replace(0, test['sc_w'].mean(), inplace=True)
test['three_g'].replace(0, test['three_g'].mean(), inplace=True)
test['wifi'].replace(0, test['wifi'].mean(), inplace=True)
test['fc'].replace(0, test['fc'].mean(), inplace=True)

### as there are irrelevent values in above columns replace them with mean values

In [42]:
test.all()

battery_power    True
fc               True
int_memory       True
pc               True
px_height        True
px_width         True
ram              True
sc_h             True
sc_w             True
three_g          True
wifi             True
dtype: bool

## X_TEST

### After dropping the certain columns in the test dataset put the remaining columns into x_test

In [43]:
x_test=test

In [44]:
x_test.shape

(1000, 11)

## Applying SVM algorithm to the given data set to predict values for test data set (as svm alogorithm is the best approach)

In [45]:
from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=0)
classifier.fit(x_train,y_train['price_range'])

SVC(kernel='linear', random_state=0)

In [46]:
y_pred=classifier.predict(x_test)

### predicted values for test data set

In [47]:
y_pred

array([3, 3, 3, 3, 1, 3, 3, 1, 3, 0, 3, 3, 0, 0, 2, 0, 2, 1, 3, 2, 1, 3,
       1, 1, 3, 0, 2, 0, 3, 0, 2, 0, 3, 0, 1, 1, 3, 1, 2, 1, 1, 2, 0, 0,
       0, 1, 0, 3, 1, 2, 1, 0, 3, 0, 3, 1, 3, 1, 1, 3, 3, 3, 0, 1, 1, 1,
       2, 3, 1, 2, 1, 2, 2, 3, 3, 0, 2, 0, 2, 3, 0, 3, 3, 0, 3, 0, 3, 1,
       3, 0, 1, 2, 2, 1, 2, 2, 0, 2, 1, 2, 1, 0, 0, 3, 0, 2, 0, 1, 2, 3,
       3, 3, 1, 3, 3, 3, 3, 2, 3, 0, 0, 3, 2, 1, 2, 0, 3, 2, 3, 2, 0, 2,
       1, 1, 3, 1, 1, 0, 3, 2, 1, 2, 1, 3, 2, 3, 3, 3, 2, 3, 2, 3, 1, 0,
       3, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 1, 0, 3, 0, 0, 0, 2, 1, 0, 1,
       0, 0, 1, 2, 1, 0, 0, 1, 1, 2, 2, 1, 0, 0, 0, 1, 0, 3, 1, 0, 2, 2,
       2, 3, 1, 1, 3, 2, 3, 2, 2, 1, 0, 0, 1, 3, 0, 2, 3, 3, 0, 2, 0, 3,
       2, 3, 3, 1, 0, 1, 0, 3, 0, 1, 0, 2, 2, 1, 2, 1, 3, 0, 3, 1, 2, 0,
       0, 2, 1, 3, 3, 3, 1, 1, 3, 0, 0, 2, 3, 3, 1, 3, 1, 1, 3, 2, 1, 2,
       3, 3, 3, 1, 0, 0, 2, 3, 1, 1, 3, 2, 0, 3, 0, 0, 3, 1, 0, 3, 2, 3,
       3, 2, 1, 3, 3, 2, 3, 1, 2, 1, 2, 0, 2, 3, 1, 0, 0, 3, 0, 3, 0, 1,
       2, 0, 2, 3, 1, 3, 2, 2, 1, 2, 0, 0, 0, 1, 3, 2, 0, 0, 0, 3, 2, 0,
       2, 3, 1, 2, 2, 2, 3, 1, 3, 3, 2, 2, 2, 3, 3, 0, 3, 1, 3, 1, 3, 1,
       3, 3, 0, 1, 0, 3, 1, 3, 2, 3, 0, 0, 0, 0, 2, 0, 0, 2, 2, 1, 2, 2,
       2, 0, 1, 0, 0, 3, 2, 0, 3, 1, 2, 2, 1, 2, 3, 1, 1, 2, 2, 1, 2, 0,
       1, 1, 0, 3, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 2, 3, 2, 3, 0, 3,
       0, 3, 0, 1, 1, 0, 2, 0, 3, 2, 3, 3, 1, 3, 1, 3, 1, 3, 2, 0, 1, 2,
       1, 1, 0, 0, 0, 1, 2, 1, 0, 3, 2, 0, 2, 2, 0, 0, 3, 1, 2, 0, 3, 3,
       3, 0, 3, 0, 2, 3, 2, 3, 0, 2, 0, 2, 3, 0, 1, 1, 0, 0, 1, 2, 1, 3,
       3, 3, 2, 3, 1, 2, 2, 3, 3, 3, 2, 0, 2, 1, 2, 2, 1, 0, 2, 2, 0, 0,
       0, 3, 1, 0, 2, 2, 2, 0, 3, 1, 2, 2, 1, 3, 0, 2, 3, 0, 1, 1, 3, 3,
       1, 1, 2, 3, 2, 0, 2, 0, 2, 0, 3, 3, 1, 3, 2, 2, 3, 0, 1, 2, 3, 1,
       3, 2, 3, 1, 1, 0, 0, 3, 1, 0, 3, 2, 3, 2, 0, 3, 3, 3, 2, 3, 3, 1,
       2, 0, 2, 2, 3, 1, 0, 1, 1, 2, 2, 1, 0, 0, 2, 2, 3, 2, 0, 2, 1, 3,
       3, 0, 1, 3, 0, 2, 1, 1, 0, 0, 2, 1, 0, 1, 1, 2, 2, 0, 2, 2, 1, 0,
       3, 0, 0, 3, 2, 0, 0, 0, 0, 0, 3, 0, 3, 1, 3, 2, 1, 3, 2, 0, 1, 0,
       3, 2, 3, 2, 0, 3, 0, 2, 0, 2, 0, 0, 1, 1, 1, 2, 1, 3, 1, 3, 2, 2,
       1, 3, 2, 0, 1, 2, 0, 3, 3, 0, 2, 1, 1, 2, 0, 3, 2, 0, 3, 2, 3, 0,
       0, 3, 0, 2, 2, 3, 2, 2, 2, 2, 1, 2, 3, 0, 1, 0, 1, 2, 2, 0, 0, 1,
       0, 0, 3, 1, 1, 2, 0, 0, 1, 1, 3, 0, 3, 2, 3, 0, 0, 1, 2, 2, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 3, 3, 0, 3, 1, 1, 3, 0, 1, 0, 2, 2, 0, 3, 1,
       0, 3, 0, 1, 0, 3, 3, 3, 2, 3, 0, 3, 2, 0, 0, 0, 3, 3, 2, 0, 2, 1,
       3, 0, 0, 2, 2, 0, 3, 1, 2, 1, 1, 1, 3, 1, 1, 1, 2, 1, 0, 2, 2, 0,
       2, 0, 0, 0, 0, 2, 3, 3, 3, 0, 1, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 3,
       2, 2, 1, 2, 0, 2, 1, 3, 0, 0, 3, 2, 3, 0, 0, 2, 3, 3, 1, 3, 2, 1,
       0, 0, 3, 3, 0, 3, 0, 0, 0, 2, 2, 1, 2, 0, 3, 2, 1, 2, 3, 3, 0, 1,
       1, 2, 1, 2, 2, 0, 1, 3, 1, 1, 3, 0, 2, 3, 2, 1, 1, 1, 3, 3, 0, 2,
       3, 0, 2, 3, 3, 2, 2, 3, 2, 0, 1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1,
       0, 1, 3, 1, 0, 1, 2, 3, 1, 0, 0, 3, 2, 2, 3, 0, 3, 3, 2, 1, 3, 0,
       1, 3, 1, 1, 1, 1, 3, 2, 0, 3, 0, 2, 3, 0, 3, 2, 3, 3, 1, 0, 2, 3,
       1, 0, 2, 1, 2, 1, 2, 0, 2, 2, 0, 2, 3, 2, 3, 0, 2, 1, 1, 2, 2, 3,
       3, 0, 2, 1, 2, 1, 3, 1, 0, 3, 0, 1, 0, 0, 3, 3, 2, 0, 0, 0, 0, 3,
       2, 3, 3, 0, 0, 2, 1, 0, 2, 2], dtype=int64)

In [48]:
y_pred=pd.DataFrame(y_pred)

In [49]:
y_pred

     0
0    3
1    3
2    3
3    3
4    1
..  ..
995  2
996  1
997  0
998  2
999  2

[1000 rows x 1 columns]